backend:
  name: git-gateway
  branch: main

media_folder: "src/assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/blogs"
    create: true
    
    identifier_field: title 
    slug: "{{year}}-{{month}}-{{day}}-{{title | slugify}}"
    fields:
      - { label: "Title", name: "title", widget: "string", required: true }
      - { label: "Description", name: "description", widget: "text", pattern: ["^.{0,200}$", "Must be 200 characters or fewer."], required: false }
      - name: "date"
        label: "Date"
        widget: "datetime"
        format: "YYYY-MM-DD"
        time_format: false
        date_format: "YYYY-MM-DD"
        picker_utc: false
        default: "{% commit_date %}"
      - name: "updated"
        label: "Last Updated" 
        widget: "meta"
        meta: { type: "updatedAt", format: "YYYY-MM-DD HH:mm:ss Z" }
      - { label: "Author", name: "author", widget: "string", default: "Mark Russell", required: false }
      - { label: "Featured Image", name: "image", widget: "image", required: false}
      - { label: "Image Alt Text", name: "imageAlt", widget: "string", required: false}
      - { label: "Tags", name: "tags", widget: "list", field: {label: "Tag", name: "tag", widget: "string"}, required: false}
      - { label: "Featured", name: "featured", widget: "boolean", hint: "Set to true to highlight on the front page.", default: false, required: false}
      - { label: "Layout", name: "layout", widget:"hidden", default: "post.njk"}
      - { label: "Body", name: "body", widget: "markdown", required: false } 

  - name: "books"
    label: "Books"
    folder: "src/books"
    create: true
    identifier_field: title 
    slug: "{{year}}-{{month}}-{{day}}-{{title | slugify}}"
    fields:
      - { label: "Title", name: "title", widget: "string", required: true }
      - name: "date"
        label: "Date"
        widget: "datetime"
        format: "YYYY-MM-DD"
        time_format: false
        date_format: "YYYY-MM-DD"
        picker_utc: false
        default: "{% commit_date %}"
      - { label: "Artist", name: "artist", widget: "string", required: false }
      - { label: "Book Cover Image", name: "image", widget: "image", required: false, hint: "Upload the book cover image."}
      - { label: "Purchase Link", name: "link", widget: "string", required: false, hint: "Purchase link (e.g., Amazon URL)"}
      - { label: "Display Order", name: "order", widget: "number", required: false, default: 5, value_type: "int", hint: "Sets display priority (lower number appears closer to the top)"}
      - { label: "Quote Source", name: "quote", widget: "string", required: false, hint: "Source of the featured quote (e.g., 'NPR news')"}
      - { label: "permalink", name: "permalink", widget: "hidden", default: false}
      - {label: "Quote Text", name: "body", widget: "text", required: false, hint: "include quotes if needed."}