backend:
  name: git-gateway
  branch: main

media_folder: "src/assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/blogs"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{title | slugify}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "description", name: "description", widget: "string", pattern: ["^.{0,200}$", "Must be 200 characters or fewer."]}
      - { label: "Date", name: "date", widget: "datetime", hint: "will default to submission time, only choose time different", required: false,  default: now}
      - { label: "updated", name: "updated", label: "Last Updated", widget: "meta", meta: { type: "updatedAt", format: "YYYY-MM-DD HH:mm:ss Z" } }
      - { label: "author", name: "author", widget: "string", default: "Mark Russell" }
      - { label: "image", name: "image", widget: "image"}
      - { label: "Image Alt Text", name: "imageAlt", widget: "string", required: false}
      - { label: "Tags", name: "tags", widget: "list", field: {label: "Tag", name: "tag", widget: "string"}, required: false} 
      - { label: "Featured", name: "featured", widget: "boolean", hint: "set to true for new/coming soon front page", default: false} 
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "books"
    label: "Books"
    folder: "src/books"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{title | slugify}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime", required: false, hint: "will deftaul to subission time if no date is picked", default: now }
      - { label: "artist", name: "artist", widget: "string" }
      - { label: "image", name: "image", widget: "image"}      
      - { label: "link", name: "link", widget: "string", hint: "purchase link (have been using Amazon)"}
      - { label: "order", name: "order", widget: "number", required: false, default: 5,   value_type: "int", hint: "sets display priority for book- 1 = top of list, 10 = bottom of list"} 
      - { label: "quote", name: "quote", widget: "string", required: false, hint: "only use if quoting an article or person in the body of the message"}
      - { label: "Body", name: "body", widget: "string",  hint: "use quotation marks if using a quote", pattern: ["^.{0,250}$", "Must be 250 characters or fewer."] }
---
